"""Agrodomain v2 core package exports."""

from __future__ import annotations

from importlib import import_module
from typing import Iterable

from .country_pack import CountryPolicy, resolve_country_policy
from .ledger import (
    LedgerEntry,
    WalletLedgerService,
    assert_ledger_invariants,
    validate_ledger_invariants,
)

__all__ = [
    "CountryPolicy",
    "LedgerEntry",
    "WalletLedgerService",
    "assert_ledger_invariants",
    "resolve_country_policy",
    "validate_ledger_invariants",
]


def _export_optional(module_name: str, symbols: Iterable[str]) -> None:
    """Expose optional symbols without failing package import for missing modules."""
    try:
        module = import_module(f"{__name__}.{module_name}")
    except ModuleNotFoundError as exc:
        if exc.name != f"{__name__}.{module_name}":
            raise
        return

    for symbol in symbols:
        if hasattr(module, symbol):
            globals()[symbol] = getattr(module, symbol)
            __all__.append(symbol)


_export_optional(
    "identity_consent",
    (
        "ConsentCapture",
        "IdentityConsentError",
        "IdentityConsentRecord",
        "IdentityConsentService",
        "IdentityState",
    ),
)
_export_optional(
    "frontend_app_shell",
    (
        "AppRole",
        "AppShellSnapshot",
        "FrontendAppShellError",
        "NavigationItem",
        "QueueSummary",
        "ROLE_HOME_ROUTES",
        "ShellAuditResult",
        "ShellLayout",
        "UnifiedAppShell",
    ),
)
_export_optional(
    "frontend_consent_ui",
    (
        "ConsentRouteDecision",
        "ConsentStep",
        "ConsentSurface",
        "ConsentUiAuditResult",
        "FrontendConsentUi",
        "FrontendConsentUiError",
    ),
)
_export_optional(
    "frontend_design_tokens",
    (
        "FrontendDesignTokenBundle",
        "FrontendDesignTokenError",
        "FrontendThemeAudit",
        "SurfaceTokenBinding",
        "build_default_frontend_design_tokens",
    ),
)
_export_optional(
    "frontend_state_primitives",
    (
        "FrontendStatePrimitiveError",
        "FrontendStatePrimitiveLibrary",
        "StateCoverageReport",
        "StatePrimitive",
        "build_default_frontend_state_primitives",
    ),
)
_export_optional(
    "frontend_accessibility_primitives",
    (
        "FieldHelperCopy",
        "FocusPath",
        "FrontendAccessibilityPrimitiveError",
        "FrontendAccessibilityPrimitives",
        "build_default_frontend_accessibility_primitives",
    ),
)
_export_optional(
    "frontend_home_queues",
    (
        "FrontendHomeQueueBuilder",
        "FrontendHomeQueueError",
        "HomeQueueAudit",
        "HomeQueueSurface",
        "HomeQueueTask",
    ),
)
_export_optional(
    "frontend_listing_routes",
    (
        "FrontendListingRouteError",
        "FrontendListingRoutes",
        "ListingBrowseSurface",
        "ListingCard",
        "ListingDetailSurface",
        "ListingRouteAudit",
    ),
)
_export_optional(
    "frontend_listing_wizard",
    (
        "FrontendListingWizard",
        "FrontendListingWizardError",
        "ListingWizardAudit",
        "ListingWizardStep",
        "ListingWizardSurface",
    ),
)
_export_optional(
    "frontend_negotiation_ui",
    (
        "FrontendNegotiationUi",
        "FrontendNegotiationUiError",
        "NegotiationInboxItem",
        "NegotiationThreadSurface",
        "NegotiationUiAudit",
    ),
)
_export_optional(
    "frontend_escrow_wallet_center",
    (
        "EscrowTimelineEntry",
        "EscrowWalletAudit",
        "EscrowWalletSurface",
        "FrontendEscrowWalletCenter",
        "FrontendEscrowWalletError",
        "WalletActivityRow",
    ),
)
_export_optional(
    "frontend_advisory_routes",
    (
        "AdvisoryAnswerSurface",
        "AdvisoryComposerSurface",
        "AdvisoryRouteAudit",
        "FrontendAdvisoryRouteError",
        "FrontendAdvisoryRoutes",
    ),
)
_export_optional(
    "frontend_citation_drawer",
    (
        "CitationDrawerAudit",
        "CitationDrawerSurface",
        "FrontendCitationDrawer",
        "FrontendCitationDrawerError",
        "ProofRow",
    ),
)
_export_optional(
    "frontend_climate_alert_center",
    (
        "ClimateAlertAudit",
        "ClimateAlertDetailSurface",
        "ClimateAlertListItem",
        "FrontendClimateAlertCenter",
        "FrontendClimateAlertError",
    ),
)
_export_optional(
    "frontend_finance_queue",
    (
        "FinanceDecisionDetailSurface",
        "FinanceQueueAudit",
        "FinanceQueueListItem",
        "FinanceQueueSurface",
        "FrontendFinanceQueue",
        "FrontendFinanceQueueError",
    ),
)
_export_optional(
    "frontend_traceability_routes",
    (
        "FrontendTraceabilityRouteError",
        "FrontendTraceabilityRoutes",
        "TraceabilityRouteAudit",
        "TraceabilityTimelineEntry",
        "TraceabilityTimelineSurface",
    ),
)
_export_optional(
    "frontend_evidence_capture_queue",
    (
        "CaptureMethodOption",
        "EvidenceCaptureAudit",
        "EvidenceCaptureSurface",
        "EvidenceUploadQueueItem",
        "FrontendEvidenceCaptureError",
        "FrontendEvidenceCaptureQueue",
    ),
)
_export_optional(
    "frontend_offline_conflict_ui",
    (
        "ConflictDetailSurface",
        "FrontendOfflineConflictError",
        "FrontendOfflineConflictUi",
        "OfflineConflictAudit",
        "OfflineOutboxSurface",
        "OutboxItem",
    ),
)
_export_optional(
    "frontend_notifications_center",
    (
        "FrontendNotificationsCenter",
        "FrontendNotificationsCenterError",
        "NotificationCenterItem",
        "NotificationsCenterAudit",
        "NotificationsCenterSurface",
    ),
)
_export_optional(
    "frontend_cooperative_ops",
    (
        "CooperativeDispatchRow",
        "CooperativeMemberTask",
        "CooperativeOperationsSurface",
        "CooperativeOpsAudit",
        "FrontendCooperativeOperations",
        "FrontendCooperativeOpsError",
    ),
)
_export_optional(
    "frontend_advisor_workbench",
    (
        "AdvisorInterventionLogRow",
        "AdvisorQueueItem",
        "AdvisorWorkbenchAudit",
        "AdvisorWorkbenchSurface",
        "FrontendAdvisorWorkbench",
        "FrontendAdvisorWorkbenchError",
    ),
)
_export_optional(
    "frontend_admin_analytics",
    (
        "AdminAnalyticsAudit",
        "AdminAnalyticsSurface",
        "AnalyticsMetricCard",
        "FrontendAdminAnalytics",
        "FrontendAdminAnalyticsError",
        "ObservabilityAlertRow",
    ),
)
_export_optional(
    "frontend_contract_adapters",
    (
        "FrontendContractAdapterError",
        "FrontendContractAdapters",
        "FrontendContractValidationReport",
        "FrontendDtoIssue",
        "FrontendMutationDto",
        "FrontendRouteDtoEnvelope",
    ),
)
_export_optional(
    "frontend_route_services",
    (
        "FrontendMutationReceipt",
        "FrontendRouteDataServices",
        "FrontendRouteLoaderRequest",
        "FrontendRouteLoaderResult",
        "FrontendRouteServiceError",
    ),
)
_export_optional(
    "frontend_performance_budgets",
    (
        "FrontendBudgetEvaluation",
        "FrontendPerformanceBudgetError",
        "FrontendPerformanceBudgetHarness",
        "FrontendRouteBudget",
        "FrontendRouteObservation",
    ),
)
_export_optional(
    "frontend_playwright_harness",
    (
        "FrontendPlaywrightHarness",
        "FrontendPlaywrightHarnessError",
        "FrontendPlaywrightObservation",
        "FrontendPlaywrightScenario",
        "FrontendPlaywrightSuiteReport",
        "FrontendScenarioKind",
    ),
)
_export_optional(
    "frontend_architecture_review_gate",
    (
        "FrontendAdapterReview",
        "FrontendArchitectureCheck",
        "FrontendArchitectureChecklistItem",
        "FrontendArchitectureReviewError",
        "FrontendArchitectureReviewGate",
        "FrontendArchitectureReviewOutcome",
        "FrontendArchitectureReviewRequest",
        "FrontendAutomationReview",
        "FrontendBudgetReview",
        "FrontendRouteBoundary",
    ),
)
_export_optional(
    "frontend_plan_traceability_review",
    (
        "FrontendBeadTrace",
        "FrontendPlanTraceabilityError",
        "FrontendPlanTraceabilityOutcome",
        "FrontendPlanTraceabilityRequest",
        "FrontendPlanTraceabilityReview",
        "FrontendTraceabilityCheck",
        "FrontendTraceabilityChecklistItem",
    ),
)
_export_optional(
    "adversarial_intelligence_gate",
    (
        "AdversarialCheck",
        "AdversarialChecklistItem",
        "AdversarialGateOutcome",
        "AdversarialGateRequest",
        "AdversarialIntelligenceGate",
        "AdversarialIntelligenceGateError",
        "REQUIRED_TRACEABILITY_IDS",
    ),
)
_export_optional(
    "agent_eval",
    (
        "AgentEvaluationHarness",
        "AgentEvalError",
        "AgentTrace",
        "EvalFixture",
        "EvalMetric",
        "FixtureEvaluation",
        "HallucinationPolicy",
        "HarnessEvaluationReport",
        "MetricScore",
    ),
)
_export_optional(
    "audit_events",
    (
        "AppendOnlyAuditEventWriter",
        "AuditEvent",
        "AuditEventSchemaError",
        "AuditLogIntegrityError",
        "compute_event_hash",
        "validate_persisted_audit_record",
    ),
)
_export_optional("audit_logger", ("ImmutableAuditLogger",))
_export_optional(
    "escrow",
    (
        "EscrowError",
        "EscrowEvent",
        "EscrowFundingStatus",
        "EscrowOrchestrationService",
        "EscrowRecord",
        "EscrowState",
    ),
)
_export_optional(
    "advisory_retrieval",
    (
        "AdvisoryRetrievalContract",
        "AdvisoryRetrievalContractError",
        "AdvisoryRetrievalRequest",
        "AdvisoryRetrievalResult",
        "CitationMetadata",
        "VettedKnowledgeSource",
    ),
)
_export_optional(
    "listings",
    (
        "CommodityListing",
        "CreateListingCommand",
        "CreateListingPayload",
        "ListingApiContract",
        "ListingContractError",
        "ListingLifecycleError",
        "ListingStatus",
        "UpdateListingCommand",
        "UpdateListingPayload",
    ),
)
_export_optional(
    "negotiation",
    (
        "ConfirmationCheckpoint",
        "NegotiationError",
        "NegotiationState",
        "NegotiationThread",
        "NegotiationWorkflow",
        "OfferBid",
    ),
)
_export_optional(
    "policy_guardrails",
    (
        "AgentPolicyGuardrailEngine",
        "DEFAULT_POLICY_DECISION_MATRIX",
        "DEFAULT_TOOL_POLICY_RULES",
        "PolicyDecision",
        "PolicyDecisionMatrix",
        "PolicyEvaluationInput",
        "PolicyOutcome",
        "RiskLevel",
        "ToolPolicyRule",
        "evaluate_allow_deny",
    ),
)
_export_optional(
    "reviewer_workflow",
    (
        "ReviewerAgentDecisionWorkflow",
        "ReviewerDecision",
        "ReviewerDecisionOutcome",
        "ReviewerDecisionRequest",
        "ReviewerWorkflowError",
    ),
)
_export_optional(
    "verifier_loop",
    (
        "VerifierDecision",
        "VerifierDecisionLog",
        "VerifierLoopError",
        "VerifierLoopOutcome",
        "VerifierLoopRequest",
        "VerifierLoopRuntime",
        "VerifierState",
    ),
)
_export_optional(
    "planning_loop",
    (
        "ExecutionGateOutcome",
        "IntentClass",
        "PhaseCheckpointEnforcer",
        "PhaseCheckpointError",
        "PlannerTriggerInput",
        "PlannerTriggerOutcome",
        "PlanningCheckpoint",
        "PlanningLoopQualityEngine",
        "RiskClass",
    ),
)
_export_optional(
    "plan_adversarial_review_gate",
    (
        "BeadDesignReview",
        "PlanAdversarialReviewError",
        "PlanAdversarialReviewGate",
        "PlanReviewCheck",
        "PlanReviewChecklistItem",
        "PlanReviewOutcome",
        "PlanReviewRequest",
    ),
)
_export_optional(
    "architecture_adversarial_review_gate",
    (
        "ArchitectureAdversarialReviewError",
        "ArchitectureAdversarialReviewGate",
        "ArchitectureReviewCheck",
        "ArchitectureReviewChecklistItem",
        "ArchitectureReviewOutcome",
        "ArchitectureReviewRequest",
        "DeploymentReview",
        "ScaleReview",
        "SecurityControlReview",
        "ServiceBoundaryReview",
    ),
)
_export_optional(
    "tool_contracts",
    (
        "ContractField",
        "ContractValueType",
        "ToolContract",
        "ToolContractError",
        "ToolContractRegistry",
    ),
)
_export_optional(
    "multi_channel_qa_harness",
    (
        "HarnessChannel",
        "HarnessExecution",
        "HarnessSuiteReport",
        "JourneyFixture",
        "MultiChannelQAHarness",
        "MultiChannelQAHarnessError",
        "ScenarioKind",
        "build_default_multi_channel_qa_harness",
    ),
)
_export_optional(
    "ussd_adapter",
    (
        "UssdAdapterContract",
        "UssdAdapterError",
        "UssdMenu",
        "UssdMenuOption",
        "UssdResponse",
        "UssdSession",
        "UssdSessionStatus",
        "build_default_ussd_adapter",
    ),
)
_export_optional(
    "interaction_feedback_library",
    (
        "CriticalFlow",
        "FeedbackDecision",
        "FeedbackPattern",
        "InteractionFeedbackError",
        "InteractionFeedbackLibrary",
        "InteractionState",
        "build_default_interaction_feedback_library",
    ),
)
_export_optional(
    "accessibility_readability_pack",
    (
        "AccessibilityAuditResult",
        "AccessibilityReadabilityCompliancePack",
        "AccessibilityReadabilityError",
        "AccessibilityReviewItem",
        "AccessibilityStandard",
        "AccessibilityWorkflowReport",
        "LiteracyBand",
        "build_default_accessibility_readability_pack",
    ),
)
_export_optional(
    "mobile_api_profile",
    (
        "MobileApiProfile",
        "MobileApiProfileError",
        "MobileApiProfileRegistry",
        "PaginationPolicy",
        "PayloadBudget",
        "PayloadBudgetResult",
        "ResumableOperation",
    ),
)
_export_optional(
    "offline_action_queue",
    (
        "ConflictState",
        "OfflineAction",
        "OfflineActionQueue",
        "OfflineActionQueueError",
        "OfflineActionStatus",
        "QueueTelemetryRecord",
        "ReplayDisposition",
        "ReplayResult",
    ),
)
_export_optional(
    "sync_conflict_resolver",
    (
        "ClientAction",
        "ConflictAuditRecord",
        "ConflictResolutionPolicy",
        "SessionParityState",
        "SyncConflictRequest",
        "SyncConflictResolution",
        "SyncConflictResolverError",
        "SyncConflictResolverPolicy",
        "SyncConflictType",
        "UserResolutionState",
    ),
)
_export_optional(
    "device_capability_layer",
    (
        "CapabilityAvailability",
        "CapabilityExecutionPlan",
        "CapabilityTelemetryRecord",
        "CapabilityType",
        "DeviceCapabilityAbstractionLayer",
        "DeviceCapabilityAdapter",
        "DeviceCapabilityContract",
        "DeviceCapabilityError",
        "DeviceCapabilityRequest",
        "ExecutionMode",
        "PermissionState",
    ),
)
_export_optional(
    "notification_broker",
    (
        "BrokerChannel",
        "ChannelDelivery",
        "DeliveryState",
        "NotificationBroker",
        "NotificationBrokerError",
        "NotificationBrokerPlan",
        "NotificationBrokerRequest",
        "NotificationIntentType",
        "NotificationRecipientProfile",
    ),
)
_export_optional(
    "android_performance_harness",
    (
        "AndroidDataCheckId",
        "AndroidJourneyId",
        "AndroidMatrixId",
        "AndroidPerformanceHarnessError",
        "AndroidScenarioFixture",
        "BackgroundProfile",
        "HarnessEvaluation",
        "HarnessSuiteReport",
        "LowEndAndroidPerformanceHarness",
        "NetworkProfile",
        "PerformanceBudget",
        "ScenarioObservation",
        "build_default_android_harness",
    ),
)
_export_optional(
    "android_mobile_ux_harness",
    (
        "AndroidMobileUxHarnessError",
        "AndroidUxScenarioEvaluation",
        "AndroidUxScenarioFixture",
        "AndroidUxScenarioId",
        "AndroidUxScenarioObservation",
        "AndroidUxStateObservation",
        "AndroidUxSuiteReport",
        "LowEndAndroidMobileUxHarness",
        "build_default_android_mobile_ux_harness",
    ),
)
_export_optional(
    "ux_excellence_review_gate",
    (
        "ConversionMetric",
        "ReviewFindingSeverity",
        "UxExcellenceDesignReviewGate",
        "UxExcellenceReviewError",
        "UxReviewCheck",
        "UxReviewChecklistItem",
        "UxReviewFinding",
        "UxReviewOutcome",
        "UxReviewPhase",
        "UxReviewRequest",
    ),
)
_export_optional(
    "climate_risk_ingestion",
    (
        "ClimateIngestRecord",
        "ClimateRiskIngestionError",
        "ClimateRiskIngestionPipeline",
        "ClimateRiskSignal",
        "ClimateSourceType",
    ),
)
_export_optional(
    "climate_alert_rules",
    (
        "AlertSeverity",
        "ClimateAlertDecision",
        "ClimateAlertRule",
        "ClimateAlertRulesEngine",
        "ClimateAlertRulesError",
        "FarmClimateContext",
        "ThresholdOperator",
        "default_climate_alert_rules",
    ),
)
_export_optional(
    "device_registry",
    (
        "DeviceClass",
        "DeviceIdentity",
        "DeviceRegistryError",
        "DeviceRegistryRecord",
        "DeviceRegistryService",
        "DeviceStatus",
        "DeviceStatusChange",
    ),
)
_export_optional(
    "mrv_evidence_service",
    (
        "EvidenceAssumption",
        "EvidenceProvenance",
        "MrvEvidenceError",
        "MrvEvidenceRecord",
        "MrvEvidenceRecordService",
    ),
)
_export_optional(
    "model_router",
    (
        "BudgetGuardrailState",
        "InferenceStage",
        "ModelRouteDecision",
        "ModelRouteError",
        "ModelRouteLog",
        "ModelRouteOutcome",
        "ModelRouteRequest",
        "ModelRouterBudgetPolicy",
        "ModelRouterGuardrails",
        "ModelTier",
    ),
)
_export_optional(
    "memory_service",
    (
        "DEFAULT_FRESHNESS_THRESHOLDS",
        "FreshnessState",
        "FreshnessThreshold",
        "MemoryFreshness",
        "MemoryRecord",
        "MemoryServiceError",
        "MemoryType",
        "StoredMemoryRecord",
        "TypedMemoryService",
    ),
)
_export_optional(
    "memory_selector",
    (
        "MemorySelectionOutcome",
        "MemorySelectionRequest",
        "MemorySelector",
        "MemorySelectorError",
        "SelectedMemory",
    ),
)
_export_optional(
    "finance_partner_adapter",
    (
        "FinanceDecisionOutcome",
        "FinanceDecisionType",
        "FinancePartnerAdapterError",
        "FinancePartnerConfig",
        "FinancePartnerDecisionAdapter",
        "FinancePartnerDecisionRequest",
        "FinancePartnerDecisionResponse",
        "ResponsibilityBoundary",
    ),
)
_export_optional(
    "insurance_trigger_registry",
    (
        "InsuranceParametricTriggerRegistry",
        "InsuranceTriggerRegistryError",
        "ParametricPayoutEvent",
        "ParametricTriggerDefinition",
        "ParametricTriggerThreshold",
        "TriggerOperator",
    ),
)
_export_optional(
    "finance_hitl_console",
    (
        "ApprovalAction",
        "ApprovalConsoleSnapshot",
        "ApprovalItemType",
        "ApprovalQueueItem",
        "ApprovalState",
        "ConsoleViewState",
        "FinanceHitlConsoleError",
        "FinanceInsuranceHitlApprovalConsole",
        "build_default_console_policy_engine",
    ),
)
_export_optional(
    "multilingual_delivery",
    (
        "DeliveryAudience",
        "LocalizedCopy",
        "MultilingualDeliveryError",
        "MultilingualDeliveryFramework",
        "MultilingualDeliveryPlan",
        "ReadabilityAssessment",
        "ReadabilityState",
    ),
)
_export_optional(
    "settlement_notifications",
    (
        "ChannelDeliveryPlan",
        "NotificationChannel",
        "NotificationFeedbackState",
        "NotificationRecipient",
        "SettlementNotificationError",
        "SettlementNotificationPlan",
        "SettlementNotificationPlanner",
        "SettlementNotificationRequest",
    ),
)
_export_optional(
    "sensor_event_schema",
    (
        "SensorEventContract",
        "SensorEventEnvelope",
        "SensorEventProvenance",
        "SensorEventSchemaError",
        "SensorEventType",
        "SensorTransport",
        "validate_registry_dependency",
    ),
)
_export_optional(
    "telemetry_ingestion_api",
    (
        "TelemetryIngestionApiError",
        "TelemetryIngestionApiProfile",
        "TelemetryIngestionBatch",
        "TelemetryIngestionReceipt",
        "TelemetryResumeToken",
    ),
)
_export_optional(
    "event_bus_partitioning",
    (
        "EventBusPartitioningError",
        "EventBusTopicPartitioningModel",
        "EventBusTopicRoute",
        "TelemetryTopicFamily",
    ),
)
_export_optional(
    "digital_twin_governance",
    (
        "DigitalTwinGovernanceError",
        "DigitalTwinReadinessModel",
        "TwinDataClass",
        "TwinFieldDefinition",
        "TwinGovernanceAction",
        "TwinGovernancePolicy",
        "TwinSchemaDefinition",
        "TwinStateProjection",
    ),
)
_export_optional(
    "quality_evidence_attachments",
    (
        "EvidenceAttachmentKind",
        "EvidenceEventDisplay",
        "EvidenceGallerySnapshot",
        "EvidenceGalleryViewState",
        "QualityEvidenceAttachment",
        "QualityEvidenceAttachmentError",
        "QualityEvidenceAttachmentService",
        "QualityEvidenceMetadata",
    ),
)
_export_optional(
    "enterprise_analytics_mart",
    (
        "EnterpriseAnalyticsDataMartContract",
        "EnterpriseAnalyticsDataMartError",
        "EnterpriseAnalyticsMartRow",
        "EnterpriseAnalyticsSourceBundle",
    ),
)
_export_optional(
    "partner_api_gateway",
    (
        "PartnerApiCredential",
        "PartnerApiGateway",
        "PartnerApiGatewayError",
        "PartnerApiRequest",
        "PartnerApiRoute",
        "PartnerAuthorizationDecision",
        "PartnerCredentialStatus",
        "PartnerScope",
    ),
)
_export_optional(
    "observability",
    (
        "ObservabilityError",
        "ObservabilityInstrumentationService",
        "ServiceLevelObjective",
        "SloAlertDecision",
        "SpanStatus",
        "TelemetryChannel",
        "TelemetryMetric",
        "TraceSpan",
    ),
)
_export_optional(
    "visual_language_system",
    (
        "ColorToken",
        "ComponentStyleDecision",
        "ComponentStyleRule",
        "SpacingToken",
        "TypographyRole",
        "TypographyToken",
        "VisualLanguageError",
        "VisualLanguageSystem",
        "build_default_visual_language_system",
    ),
)
_export_optional(
    "traceability_event_chain",
    (
        "TraceabilityChainEvent",
        "TraceabilityEventChainError",
        "TraceabilityEventChainService",
        "TraceabilityEventType",
    ),
)
_export_optional(
    "state_store",
    (
        "CanonicalStateStore",
        "CommandResult",
        "IdempotencyConflictError",
        "WorkflowCommand",
        "WorkflowSnapshot",
        "WorkflowTransition",
    ),
)
_export_optional(
    "whatsapp_adapter",
    (
        "InboundWhatsAppMessage",
        "ParsedWhatsAppCommand",
        "WhatsAppAdapterContract",
        "WhatsAppAdapterError",
        "WhatsAppFallbackChannel",
        "WhatsAppFallbackDecision",
        "WhatsAppIntent",
        "WhatsAppMessageType",
        "WhatsAppTemplateBinding",
    ),
)
