// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/about" | "/app" | "/app/[role]" | "/app/admin/analytics" | "/app/advisor/requests" | "/app/advisory/new" | "/app/analytics" | "/app/climate/alerts" | "/app/cooperative/dispatch" | "/app/farm" | "/app/farm/fields/[id]" | "/app/farm/inputs" | "/app/finance/queue" | "/app/fund" | "/app/fund/[id]" | "/app/fund/my-investments" | "/app/insights" | "/app/insurance" | "/app/insurance/claims/[id]" | "/app/market/listings" | "/app/market/listings/[listingId]" | "/app/market/listings/create" | "/app/market/my-listings" | "/app/market/negotiations" | "/app/market/negotiations/[id]" | "/app/notifications" | "/app/offline/conflicts/[id]" | "/app/offline/outbox" | "/app/payments/wallet" | "/app/profile" | "/app/settings" | "/app/traceability/[consignmentId]" | "/app/trucker" | "/app/trucker/loads/new" | "/app/trucker/shipments/[id]" | "/app/weather" | "/contact" | "/features" | "/offline" | "/onboarding" | "/onboarding/consent" | "/signin" | "/signup"
type AppRouteHandlerRoutes = "/healthz"
type PageRoutes = never
type LayoutRoutes = "/" | "/app" | "/app/analytics" | "/app/farm" | "/app/fund" | "/app/insurance" | "/app/trucker" | "/app/weather" | "/contact" | "/onboarding" | "/signin" | "/signup"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/about": {}
  "/app": {}
  "/app/[role]": { "role": string; }
  "/app/admin/analytics": {}
  "/app/advisor/requests": {}
  "/app/advisory/new": {}
  "/app/analytics": {}
  "/app/climate/alerts": {}
  "/app/cooperative/dispatch": {}
  "/app/farm": {}
  "/app/farm/fields/[id]": { "id": string; }
  "/app/farm/inputs": {}
  "/app/finance/queue": {}
  "/app/fund": {}
  "/app/fund/[id]": { "id": string; }
  "/app/fund/my-investments": {}
  "/app/insights": {}
  "/app/insurance": {}
  "/app/insurance/claims/[id]": { "id": string; }
  "/app/market/listings": {}
  "/app/market/listings/[listingId]": { "listingId": string; }
  "/app/market/listings/create": {}
  "/app/market/my-listings": {}
  "/app/market/negotiations": {}
  "/app/market/negotiations/[id]": { "id": string; }
  "/app/notifications": {}
  "/app/offline/conflicts/[id]": { "id": string; }
  "/app/offline/outbox": {}
  "/app/payments/wallet": {}
  "/app/profile": {}
  "/app/settings": {}
  "/app/traceability/[consignmentId]": { "consignmentId": string; }
  "/app/trucker": {}
  "/app/trucker/loads/new": {}
  "/app/trucker/shipments/[id]": { "id": string; }
  "/app/weather": {}
  "/contact": {}
  "/features": {}
  "/healthz": {}
  "/offline": {}
  "/onboarding": {}
  "/onboarding/consent": {}
  "/signin": {}
  "/signup": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/app": never
  "/app/analytics": never
  "/app/farm": never
  "/app/fund": never
  "/app/insurance": never
  "/app/trucker": never
  "/app/weather": never
  "/contact": never
  "/onboarding": never
  "/signin": never
  "/signup": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
