// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../app/about/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/about">> = Specific
  const handler = {} as typeof import("../../app/about/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/app/[role]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/[role]">> = Specific
  const handler = {} as typeof import("../../app/app/[role]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/app/admin/analytics/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/admin/analytics">> = Specific
  const handler = {} as typeof import("../../app/app/admin/analytics/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/app/advisor/requests/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/advisor/requests">> = Specific
  const handler = {} as typeof import("../../app/app/advisor/requests/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/app/advisory/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/advisory/new">> = Specific
  const handler = {} as typeof import("../../app/app/advisory/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/app/analytics/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/analytics">> = Specific
  const handler = {} as typeof import("../../app/app/analytics/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/app/climate/alerts/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/climate/alerts">> = Specific
  const handler = {} as typeof import("../../app/app/climate/alerts/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/app/cooperative/dispatch/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/cooperative/dispatch">> = Specific
  const handler = {} as typeof import("../../app/app/cooperative/dispatch/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/app/farm/fields/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/farm/fields/[id]">> = Specific
  const handler = {} as typeof import("../../app/app/farm/fields/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/app/farm/inputs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/farm/inputs">> = Specific
  const handler = {} as typeof import("../../app/app/farm/inputs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/app/farm/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/farm">> = Specific
  const handler = {} as typeof import("../../app/app/farm/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/app/finance/queue/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/finance/queue">> = Specific
  const handler = {} as typeof import("../../app/app/finance/queue/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/app/fund/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/fund/[id]">> = Specific
  const handler = {} as typeof import("../../app/app/fund/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/app/fund/my-investments/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/fund/my-investments">> = Specific
  const handler = {} as typeof import("../../app/app/fund/my-investments/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/app/fund/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/fund">> = Specific
  const handler = {} as typeof import("../../app/app/fund/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/app/insights/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/insights">> = Specific
  const handler = {} as typeof import("../../app/app/insights/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/app/insurance/claims/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/insurance/claims/[id]">> = Specific
  const handler = {} as typeof import("../../app/app/insurance/claims/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/app/insurance/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/insurance">> = Specific
  const handler = {} as typeof import("../../app/app/insurance/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/app/market/listings/[listingId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/market/listings/[listingId]">> = Specific
  const handler = {} as typeof import("../../app/app/market/listings/[listingId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/app/market/listings/create/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/market/listings/create">> = Specific
  const handler = {} as typeof import("../../app/app/market/listings/create/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/app/market/listings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/market/listings">> = Specific
  const handler = {} as typeof import("../../app/app/market/listings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/app/market/my-listings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/market/my-listings">> = Specific
  const handler = {} as typeof import("../../app/app/market/my-listings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/app/market/negotiations/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/market/negotiations/[id]">> = Specific
  const handler = {} as typeof import("../../app/app/market/negotiations/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/app/market/negotiations/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/market/negotiations">> = Specific
  const handler = {} as typeof import("../../app/app/market/negotiations/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/app/notifications/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/notifications">> = Specific
  const handler = {} as typeof import("../../app/app/notifications/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/app/offline/conflicts/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/offline/conflicts/[id]">> = Specific
  const handler = {} as typeof import("../../app/app/offline/conflicts/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/app/offline/outbox/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/offline/outbox">> = Specific
  const handler = {} as typeof import("../../app/app/offline/outbox/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app">> = Specific
  const handler = {} as typeof import("../../app/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/app/payments/wallet/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/payments/wallet">> = Specific
  const handler = {} as typeof import("../../app/app/payments/wallet/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/app/profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/profile">> = Specific
  const handler = {} as typeof import("../../app/app/profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/app/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/settings">> = Specific
  const handler = {} as typeof import("../../app/app/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/app/traceability/[consignmentId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/traceability/[consignmentId]">> = Specific
  const handler = {} as typeof import("../../app/app/traceability/[consignmentId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/app/trucker/loads/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/trucker/loads/new">> = Specific
  const handler = {} as typeof import("../../app/app/trucker/loads/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/app/trucker/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/trucker">> = Specific
  const handler = {} as typeof import("../../app/app/trucker/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/app/trucker/shipments/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/trucker/shipments/[id]">> = Specific
  const handler = {} as typeof import("../../app/app/trucker/shipments/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/app/weather/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/weather">> = Specific
  const handler = {} as typeof import("../../app/app/weather/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/contact/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/contact">> = Specific
  const handler = {} as typeof import("../../app/contact/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/features/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/features">> = Specific
  const handler = {} as typeof import("../../app/features/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/offline/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/offline">> = Specific
  const handler = {} as typeof import("../../app/offline/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/onboarding/consent/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/onboarding/consent">> = Specific
  const handler = {} as typeof import("../../app/onboarding/consent/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/onboarding/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/onboarding">> = Specific
  const handler = {} as typeof import("../../app/onboarding/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/signin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/signin">> = Specific
  const handler = {} as typeof import("../../app/signin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/signup/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/signup">> = Specific
  const handler = {} as typeof import("../../app/signup/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/healthz/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/healthz">> = Specific
  const handler = {} as typeof import("../../app/healthz/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../app/app/analytics/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/app/analytics">> = Specific
  const handler = {} as typeof import("../../app/app/analytics/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/app/farm/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/app/farm">> = Specific
  const handler = {} as typeof import("../../app/app/farm/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/app/fund/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/app/fund">> = Specific
  const handler = {} as typeof import("../../app/app/fund/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/app/insurance/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/app/insurance">> = Specific
  const handler = {} as typeof import("../../app/app/insurance/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/app">> = Specific
  const handler = {} as typeof import("../../app/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/app/trucker/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/app/trucker">> = Specific
  const handler = {} as typeof import("../../app/app/trucker/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/app/weather/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/app/weather">> = Specific
  const handler = {} as typeof import("../../app/app/weather/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/contact/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/contact">> = Specific
  const handler = {} as typeof import("../../app/contact/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/onboarding/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/onboarding">> = Specific
  const handler = {} as typeof import("../../app/onboarding/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/signin/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/signin">> = Specific
  const handler = {} as typeof import("../../app/signin/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/signup/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/signup">> = Specific
  const handler = {} as typeof import("../../app/signup/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
